version: "3.9"
services:
  rust-backend:
    env_file:
      - ./backend/.env
    build: 
      context: ./backend
      dockerfile: ./../Dockerfile/Backend/Dockerfile
    ports:
      - 4000:8083
    volumes:
      - ./backend:/backend
    tty: true
    networks:
      - mysql-network
  rust-mysql:
    env_file:
      - ./database/.env
    build: 
      context: ./database
      dockerfile: ./../Dockerfile/Database/Dockerfile
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - ./database:/database
      - ./database/conf/my.cnf:/etc/mysql/conf.d/my.cnf
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${ROOT_PASS:-root}"
      MYSQL_DATABASE: "${DB_NAME:-test}"
      MYSQL_USER: "${DB_USER:-test}"
      MYSQL_PASSWORD: "${DB_PASS:-test}"
      TZ: "${TZ:-Asia/Tokyo}"
    networks:
      - mysql-network
  rust-phpmyadmin:
    env_file:
      - ./database/.env
    build: 
      context: ./database
      dockerfile: ./../Dockerfile/PHPMyAdmin/Dockerfile
    ports:
      - "${MY_ADMIN_PORT:-8081}:80"
    links:
      - rust-mysql
    volumes:
      - ./database:/database
    restart: always
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: "${PMA_HOST:-rust-mysql}"
      PMA_USER: "${DB_USER:-test}"
      PMA_PASSWORD: "${DB_PASS:-test}"
    networks:
      - mysql-network
networks:
  mysql-network:
    driver: bridge